spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id:  # Azure Active Directory 應用程式識別碼
            client-secret:  # Azure Active Directory 金鑰值
  
azure:
  activedirectory:
    tenant-id:  # Azure Active Directory 目錄識別碼
    active-directory-groups: User # Azure Active Directory 授權的群組清單